"use client"

import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Header from '../components/Ui/Header'
import { configureStore } from '@reduxjs/toolkit'
import cartReducer from '@/redux/cartSlice';
import { Provider } from "react-redux";

const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const store = configureStore({
    reducer: {
      cart: cartReducer,
    }
  })


  return (
    <html lang="en">
      <body className={inter.className}>

        <Provider store={store}>



          <Header />

          {children}

        </Provider>


      </body>
    </html>
  )
}
